extends:
    - plugin:vue/recommended
    - eslint:recommended
    - google
env:
    browser: true
    es6: true
    commonjs: true
    node: true
parserOptions:
    sourceType: module
    ecmaVersion: 2018
rules:
    semi: ["error", "always"]
    no-console: ["error", { "allow": ["warn", "error"] }]
    max-len: warn
    vue/require-default-prop: off
    vue/return-in-computed-property: off
globals:
    WEBPACK_APP_VERSION: true
    WEBPACK_TIMESTAMP: true
